### PR TITLE
Add new pricing update

### PR DESCRIPTION
**Pull request by raghukamath**
This PR removes the cards and p10 user plan

screenshot-2018-4-18 pricing

Fixes [#13508](https://github.com/frappe/erpnext/issues/13508)

P.S. I would need help in making the hr between plans small as in my initial design, the design is shown in the issue.

### CODE REVIEW

**Comment by rmehta** [comment]
pricing amount should be in larger text size

**Comment by raghukamath** [comment]
Increased the size of the pricing text

screenshot-2018-4-18 pricing 1

**Comment by umairsy** [comment]
The updated size of price, is it not conflicting with the size of section heading itself "Small and Medium Business"?

**Comment by raghukamath** [comment]
screenshot-2018-4-19 pricing

**Pull request merged**
