### PR TITLE
fix: removed page in-app-support.md

### PR DESCRIPTION
**Pull request by shadrak98**
Removed Page in-app-support.md and introducing-in-app-support.md (dead page and had outbound link to in-app-support page).

### CODE REVIEW

**Review by abhishekbalam — COMMENTED** [review]
Also check for links to this page elsewhere

**Comment by abhishekbalam** [comment]
@shadrak98 Also try checking if the spell checker is broken and fix if it is.

**Comment by shadrak98** [comment]
Don't merge this yet

**Comment by shadrak98** [comment]
It can be merged.

**Comment by abhishekbalam** [comment]
@shadrak98 

I can see a lot of linked images and gifs in the repository still:
https://github.com/frappe/erpnext_com/tree/master/erpnext_com/public/images/in-app-support

**Review by abhishekbalam — COMMENTED** [review]
@shadrak98 

I can see a lot of linked images and gifs in the repository still:
https://github.com/frappe/erpnext_com/tree/master/erpnext_com/public/images/in-app-support

**Comment by shadrak98** [comment]
@abhishekbalam 

I have removed all the images linked to this page.

**Pull request merged**
